blank_issues_enabled: false
contact_links:
  - name: Twitter Academic Research R package issue reporting
    url: https://github.com/cjbarrie/twittterv2r
    about: Please ask and answer questions here.
